### ISSUE TITLE
stack level too deep

### ISSUE THREAD

**Issue by jpatters** [metaskills/minitest-spec-rails#104]
I'm getting an error after upgrading to Rails 6.0.3.1 from Rails 5.2.x
```
Traceback (most recent call last):
	7714: from bin/rails:6:in `<main>'
	7713: from /Users/jordan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `require'
	7712: from /Users/jordan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	7711: from /Users/jordan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `block in require'
	7710: from /Users/jordan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	7709: from /Users/jordan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	7708: from /Users/jordan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	7707: from /Users/jordan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 ... 7702 levels...
	   4: from /Users/jordan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-spec-rails-6.0.2/lib/minitest-spec-rails/parallelize.rb:17:in `describe'
	   3: from /Users/jordan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-spec-rails-6.0.2/lib/minitest-spec-rails/parallelize.rb:17:in `describe'
	   2: from /Users/jordan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-spec-rails-6.0.2/lib/minitest-spec-rails/parallelize.rb:17:in `describe'
	   1: from /Users/jordan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-spec-rails-6.0.2/lib/minitest-spec-rails/parallelize.rb:17:in `describe'
/Users/jordan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-spec-rails-6.0.2/lib/minitest-spec-rails/parallelize.rb:17:in `describe': stack level too deep (SystemStackError)
```

I tried removing all my tests and configurations in my `test_helper.rb` but this issue persisted.

Any help would be greatly appreciated. 
Thanks

**Comment by jpatters** [comment]
I believe this was caused by this having been rolled into the `minitest-rails` gem. I've solved the problem by simply removing this gem.

**Comment by metaskills** [comment]
Oh! Thanks for following up. I was testing last night and could not reproduce it.
