### ISSUE TITLE
Can't use nested describe blocks in controller tests

### ISSUE THREAD

**Issue by blowmage** [metaskills/minitest-spec-rails#11]
Here are the steps to reproduce. Create a new rails app:

```
$ rails new mts_test
$ cd mts_test/
$ echo "gem 'minitest-spec-rails'" >> Gemfile
$ bundle
$ rails g scaffold widget name:string
$ rake db:migrate
```

Now update the `test/functional/widgets_controller_test.rb` test to the following:

```
require 'test_helper'

describe WidgetsController do
  describe "index" do
    it "succeeds" do
      get :index
      assert_response :success
      refute_nil assigns(:widgets)
    end
  end
end
```

Then run your tests. The "NameError: wrong constant name index" error is from the nested describe. Try changing the describe clock's string to "index action" and you will get the error "NameError: wrong constant name index action".

```
$ rake
Rack::File headers parameter replaces cache_control after Rack 1.5.
Run options: --seed 41875

# Running tests:



Finished tests in 0.002314s, 0.0000 tests/s, 0.0000 assertions/s.

0 tests, 0 assertions, 0 failures, 0 errors, 0 skips
Rack::File headers parameter replaces cache_control after Rack 1.5.
Run options: --seed 24962

# Running tests:

E

Finished tests in 0.038663s, 25.8645 tests/s, 0.0000 assertions/s.

  1) Error:
test_0001_succeeds(WidgetsController::index):
NameError: wrong constant name index
    *GEMPATH*/activesupport-3.2.11/lib/active_support/inflector/methods.rb:230:in `const_defined?'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/inflector/methods.rb:230:in `block in constantize'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/inflector/methods.rb:229:in `each'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/inflector/methods.rb:229:in `constantize'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/inflector/methods.rb:260:in `safe_constantize'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/core_ext/string/inflections.rb:66:in `safe_constantize'
    *GEMPATH*/actionpack-3.2.11/lib/action_controller/test_case.rb:379:in `determine_default_controller_class'
    *GEMPATH*/actionpack-3.2.11/lib/action_controller/test_case.rb:374:in `controller_class'
    *GEMPATH*/actionpack-3.2.11/lib/action_controller/test_case.rb:483:in `setup_controller_request_and_response'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/callbacks.rb:418:in `_run__2957963386970996437__setup__952493641747501755__callbacks'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_setup_callbacks'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/testing/setup_and_teardown.rb:35:in `run'

  2) Error:
test_0001_succeeds(WidgetsController::index):
NoMethodError: undefined method `each' for nil:NilClass
    *GEMPATH*/activerecord-3.2.11/lib/active_record/fixtures.rb:878:in `teardown_fixtures'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `_run__2957963386970996437__teardown__952493641747501755__callbacks'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_teardown_callbacks'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
    *GEMPATH*/activesupport-3.2.11/lib/active_support/testing/setup_and_teardown.rb:44:in `run'

1 tests, 0 assertions, 0 failures, 2 errors, 0 skips
Errors running test:functionals! #<RuntimeError: Command failed with status (1): [ruby -I"lib:test" -I"*GEMPATH*/rake-10.0.3/lib" "*GEMPATH*/rake-10.0.3/lib/rake/rake_test_loader.rb" "test/functional/**/*_test.rb" ]>
Run options: --seed 65435

# Running tests:



Finished tests in 0.001056s, 0.0000 tests/s, 0.0000 assertions/s.

0 tests, 0 assertions, 0 failures, 0 errors, 0 skips
```

FWIW, this affects Helper and Mailer tests with nested describe blocks as well.

**Comment by metaskills** [comment]
I just pushed v4.7.9 which fixes this in Rails 3.0 and 3.1. Please see this commit https://github.com/metaskills/minitest-spec-rails/commit/f1e82dced915020683385dae396b13347739645b
