### ISSUE TITLE
Errors relating to action_cable in Rails 5.x

### ISSUE THREAD

**Issue by westonganger** [metaskills/minitest-spec-rails#124]
Seeing this in one of my gems test matrixes on github actions on Rails 5.2

```
`require': cannot load such file -- action_cable/channel/test_case (LoadError)
	from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/bundler/gems/minitest-spec-rails-baa2baaab568/lib/minitest-spec-rails/init/action_cable.rb:5:in `<top (required)>'
```

The readme states Rails 4.x and above is supported however the CI is only testing Rails 6.0 and above

As a gem maintainer myself, I feel its fairly easy to support Rails 5.2 in the CI. Though I find diminishing returns on the CI supporting much anything below that though.

**Comment by metaskills** [comment]
Wonder if this was the same issue as this?

- https://github.com/metaskills/minitest-spec-rails/pull/118 

Is it possible you need to update to our latest gem to future proof your CI matrix?

**Comment by westonganger** [comment]
No I do not need to upgrade. My gem has no Gemfile.lock so it is using the latest version.

This issue is regarding Rails 5.x in which action cable do not yet exist (came in rails 6)
